
class ShippingRegion < ActiveHash::Base
  self.data = [
      {:id=>1, :shipping_region=>"--"},
      {:id=>2, :shipping_region=>"北海道"},
      {:id=>3, :shipping_region=>"青森県"},
      {:id=>4, :shipping_region=>"岩手県"},
      {:id=>5, :shipping_region=>"宮城県"},
      {:id=>6, :shipping_region=>"秋田県"},
      {:id=>7, :shipping_region=>"山形県"},
      {:id=>8, :shipping_region=>"福島県"},
      {:id=>9, :shipping_region=>"茨城県"},
      {:id=>10, :shipping_region=>"栃木県"},
      {:id=>11, :shipping_region=>"群馬県"},
      {:id=>12, :shipping_region=>"埼玉県"},
      {:id=>13, :shipping_region=>"千葉県"},
      {:id=>14, :shipping_region=>"東京都"},
      {:id=>15, :shipping_region=>"神奈川県"},
      {:id=>16, :shipping_region=>"新潟県"},
      {:id=>17, :shipping_region=>"富山県"},
      {:id=>18, :shipping_region=>"石川県"},
      {:id=>19, :shipping_region=>"福井県"},
      {:id=>20, :shipping_region=>"山梨県"},
      {:id=>21, :shipping_region=>"長野県"},
      {:id=>22, :shipping_region=>"岐阜県"},
      {:id=>23, :shipping_region=>"静岡県"},
      {:id=>24, :shipping_region=>"愛知県"},
      {:id=>25, :shipping_region=>"三重県"},
      {:id=>26, :shipping_region=>"滋賀県"},
      {:id=>27, :shipping_region=>"京都府"},
      {:id=>28, :shipping_region=>"大阪府"},
      {:id=>29, :shipping_region=>"兵庫県"},
      {:id=>30, :shipping_region=>"奈良県"},
      {:id=>31, :shipping_region=>"和歌山県"},
      {:id=>32, :shipping_region=>"鳥取県"},
      {:id=>33, :shipping_region=>"島根県"},
      {:id=>34, :shipping_region=>"岡山県"},
      {:id=>35, :shipping_region=>"広島県"},
      {:id=>36, :shipping_region=>"山口県"},
      {:id=>37, :shipping_region=>"徳島県"},
      {:id=>38, :shipping_region=>"香川県"},
      {:id=>39, :shipping_region=>"愛媛県"},
      {:id=>40, :shipping_region=>"高知県"},
      {:id=>41, :shipping_region=>"福岡県"},
      {:id=>42, :shipping_region=>"佐賀県"},
      {:id=>43, :shipping_region=>"長崎県"},
      {:id=>44, :shipping_region=>"熊本県"},
      {:id=>45, :shipping_region=>"大分県"},
      {:id=>46, :shipping_region=>"宮崎県"},
      {:id=>47, :shipping_region=>"鹿児島県"},
      {:id=>48, :shipping_region=>"沖縄県"}
  ]

  include ActiveHash::Associations
  has_many :items
  end